version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    user: vscode
    working_dir: /work
    volumes:
      - ..:/work:rw,cached
    environment:
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "6g"
    profiles: [default]
  dev-nonet:
    extends: dev
    network_mode: "none"
    profiles: ["no-net"]
